# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlRdFh1sRs9Ha-6e5JRZv2TgrqkAMv8M
"""

#Chatbot using NLTK library

from nltk.chat.util import Chat, reflections

pairs = [['my name is (.*)',['Hi %1']],
         ['(hi| hello | hey|holla|hola|)', ['hey there', 'hi there','hayy', 'hoii']],
         ['(.*) in (.*) is fun',['%1 in %2 is indeed fun']],
         ['(.*)(location|city) ?',['India,Singapore']],
         ['(.*) who make you?',['Chanchal makes me by using NLTK ']],
         ['how is condition of COVID19 in (.*)',['just everything locks here in %1']],
         ['(.*) help (.*)',['I can help you']],
         ['(.*) your name?', ['My name is eshani']],]

chat = Chat(pairs, reflections)
chat.converse()

